version: '3.5'
services:
  frontend:
    build: .
    restart: always
    environment:
      - VIRTUAL_HOST=codifylab.com
      - VIRTUAL_PORT=3000
    networks:
      codifyAcademy: {}
networks:
  codifyAcademy:
    name: codifyAcademy